// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://doqrapetixnraqcibakf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvcXJhcGV0aXhucmFxY2liYWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTU1OTcsImV4cCI6MjA2OTc3MTU5N30.6zdCQBtk_rcQsxoepe-Ls7Zm0qGUVsDkA7VSTiumohU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});